name: alphanum_comparator
description: Porting of "The Alphanum Algorithm" in Dart, used to sort string lists alphanumerically.
version: 2.0.2
homepage: https://github.com/ftognetto/alphanum_comparator

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.12